title: CS 411 Doc Site
description: Documentation for CS 411
theme: just-the-docs

url: https://bsu-cs-jb.github.io/cs-411-docs

aux_links:
  Template Repository: https://github.com/bsu-cs-jb/cs-411-docs

collections:
  labs:
    output: true
  projects:
    output: true
  lectures:
    output: true
  resources:
    output: true
