title: CS 411 Doc Site
description: Documentation for CS 411
theme: just-the-docs

url: https://bsu-cs-jb.github.io/cs-411-docs
url: https://bsu-cs-jb.github.io/cs-411-docs
# baseurl: https://bsu-cs-jb.github.io/cs-411-docs
baseurl: /cs-411-docs

aux_links:
  React Native: https://reactnative.dev/docs/getting-started
  Expo: https://docs.expo.dev/
  # GitHub Repository: https://github.com/bsu-cs-jb/cs-411-docs
