title: CS 411 Doc Site
description: Documentation for CS 411
theme: just-the-docs

url: https://bsu-cs-jb.github.io/cs-411-docs
baseurl: https://bsu-cs-jb.github.io/cs-411-docs

aux_links:
  Template Repository: https://github.com/bsu-cs-jb/cs-411-docs

collections:
  labs:
    permalink: "/:collection/:title"
    output: true
  resources:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    labs:
      name: Labs
      nav_exclude: false
      search_exclude: false
    resources:
      name: Resources
      nav_exclude: false
      search_exclude: false
