title: CS 411 Course Site
description: Course site for CS 411, Fall 2023
theme: just-the-docs

# url: https://bsu-cs-jb.github.io/cs-411-docs
# baseurl: https://bsu-cs-jb.github.io/cs-411-docs
baseurl: /cs-411-docs

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Session.vim

aux_links:
  JavaScript: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide
  TypeScript: https://www.typescriptlang.org/docs/handbook/typescript-from-scratch.html
  React Native: https://reactnative.dev/docs/getting-started
  Expo: https://docs.expo.dev/
  # GitHub Repository: https://github.com/bsu-cs-jb/cs-411-docs
